### ISSUE TITLE
fatal compiler error on swift 5.7 and Swift 5.8

### ISSUE THREAD

**Issue by sebsto** [swiftlang/swift-docc-plugin#94]
### Description

using Swift Docc plugin 1.0.0, I receive fatal compilation error from Swift on 5.7 and 5.8

```
19:03:38 [2/2] Compiling plugin Swift-DocC
19:03:38 error: fatalError
```
or
```
19:01:05 Compiling plugin Swift-DocC...
19:01:05 error: emit-module command failed with exit code 1 (use -v to see invocation)
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: consecutive declarations on a line must be separated by ';'
19:01:05     private var remainingOptionsOrFlags: [String].SubSequence
19:01:05                                                  ^
19:01:05                                                  ;
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:31:50: error: expected declaration
19:01:05     private var remainingOptionsOrFlags: [String].SubSequence
19:01:05                                                  ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:01:05 public struct CommandLineArguments {
19:01:05               ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: consecutive declarations on a line must be separated by ';'
19:01:05     private var literalValues: [String].SubSequence
19:01:05                                        ^
19:01:05                                        ;
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:34:40: error: expected declaration
19:01:05     private var literalValues: [String].SubSequence
19:01:05                                        ^
19:01:05 /code/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SwiftDocCPluginUtilities/CommandLineArguments/CommandLineArguments.swift:12:15: note: in declaration of 'CommandLineArguments'
19:01:05 public struct CommandLineArguments {
19:01:05               ^
19:01:05 error: fatalError
```

This breaks our pipeline for The Swift Lambda runtime, see the automated tests for this PR : https://github.com/swift-server/swift-aws-lambda-runtime/pull/342

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Should compile on last 3 Swift versions 

### Actual behavior

```
error: fatalError
```

### Steps To Reproduce

Checkout this PR and compile with a 5.7 or 5.8 toolchain

### Swift-DocC Version Information

1.0.0

### Swift Compiler Version Information

```shell
5.7 and 5.8
```

**Comment by Kyle-Ye** [comment]
> I'm on vacation next week, away from a computer, but I can look at this when I get back if no one else has fixed this by then.

I can help fix it. But I think besides it, we need to add some CI check for each PR.

Since the Package.swift is 5.6. We need to add a CI to check build success from 5.6 to 6.0 and main.

But sadly GitHub are disabled by default and we need to add it on [ci.swift.org](http://ci.swift.org/) which I do not have permission to contribute.

> See related issue and reply [here](https://github.com/apple/swift-playdate-examples/pull/5#issuecomment-1998889689)

**Comment by anferbui** [comment]
> Since the Package.swift is 5.6. We need to add a CI to check build success from 5.6 to 6.0 and main.

@Kyle-Ye Thank you for pinging that, I don't think we want to be supporting as far back as Swift 5.6 -- as part of my fix, I will update `Package.swift` to 5.7 :)

Also, +1 on having CI for all the versions we support, to ensure changes are compatible for all.

**Comment by thomasvl** [comment]
Will there be a release soon so projects that had to pin the docc version can unpin?

**Comment by anferbui** [comment]
Just made a new release for swift-docc-plugin to get the fix out as soon as possible:
https://github.com/swiftlang/swift-docc-plugin/releases/tag/1.4.2

Pinned projects should now be able to unpin.

**Comment by thomasvl** [comment]
Thank you!
